import { supabaseQuery } from './theophany.js';

export type BudgetStatus = { budgetUsd:number; spentUsd:number; reservedUsd:number; remainingUsd:number; availableUsd:number; percentUsed:number; periodStart:string; periodEnd:string };
const rate=(name:string,fallback:number)=>{const v=Number(process.env[name]);return Number.isFinite(v)&&v>=0?v:fallback;};
const monthBounds=()=>{const n=new Date();const s=new Date(Date.UTC(n.getUTCFullYear(),n.getUTCMonth(),1));const e=new Date(Date.UTC(n.getUTCFullYear(),n.getUTCMonth()+1,1));return {start:s.toISOString(),end:e.toISOString()};};
export async function ensureBudgetTable(){await supabaseQuery('create table if not exists public.theophany_ai_usage (period_start timestamptz primary key, period_end timestamptz not null, budget_usd numeric(12,6) not null default 10, spent_usd numeric(12,6) not null default 0, reserved_usd numeric(12,6) not null default 0, updated_at timestamptz not null default now());');}
async function ensurePeriod(start:string,end:string,budget:number){await supabaseQuery('insert into public.theophany_ai_usage(period_start,period_end,budget_usd) values ('+sqlText(start)+','+sqlText(end)+','+budget+') on conflict (period_start) do update set period_end=excluded.period_end;');}
const sqlText=(v:string)=>`'${v.replace(/'/g,"''")}'`;
export async function reserveAiBudget(amountUsd:number){const {start,end}=monthBounds();const amount=Math.max(0.000001,Number(amountUsd)||0);const budget=rate('THEOPHANY_MONTHLY_AI_BUDGET_USD',10);await ensureBudgetTable();await ensurePeriod(start,end,budget);const result=await supabaseQuery<any>('update public.theophany_ai_usage set reserved_usd=reserved_usd+'+amount+', updated_at=now() where period_start='+sqlText(start)+' and budget_usd-spent_usd-reserved_usd >= '+amount+' returning period_start,budget_usd,spent_usd,reserved_usd,period_end;');if(!Array.isArray(result)||!result.length){const status=await getBudgetStatus();throw new Error('AI budget limit reached. Available this month: $'+status.availableUsd.toFixed(2)+'.');}return {periodStart:start,reservedUsd:amount};}
export async function settleAiBudget(reservation:{periodStart:string;reservedUsd:number},actualUsd:number){const actual=Math.max(0,Number(actualUsd)||0);const reserved=Math.max(0,Number(reservation.reservedUsd)||0);await supabaseQuery('update public.theophany_ai_usage set reserved_usd=greatest(0,reserved_usd-'+reserved+'), spent_usd=spent_usd+'+actual+', updated_at=now() where period_start='+sqlText(reservation.periodStart)+';');const status=await getBudgetStatus();if(status.spentUsd>status.budgetUsd)throw new Error('AI budget was exceeded by $'+(status.spentUsd-status.budgetUsd).toFixed(4)+'.');}
export async function releaseAiBudget(reservation:{periodStart:string;reservedUsd:number}){const reserved=Math.max(0,Number(reservation.reservedUsd)||0);await supabaseQuery('update public.theophany_ai_usage set reserved_usd=greatest(0,reserved_usd-'+reserved+'), updated_at=now() where period_start='+sqlText(reservation.periodStart)+';');}
export async function getBudgetStatus():Promise<BudgetStatus>{const {start,end}=monthBounds();const budget=rate('THEOPHANY_MONTHLY_AI_BUDGET_USD',10);await ensureBudgetTable();await ensurePeriod(start,end,budget);const rows=await supabaseQuery<any>('select budget_usd,spent_usd,reserved_usd,period_start,period_end from public.theophany_ai_usage where period_start='+sqlText(start)+' limit 1;');const row=Array.isArray(rows)?rows[0]:rows;const budgetUsd=Number(row?.budget_usd??budget),spentUsd=Number(row?.spent_usd??0),reservedUsd=Number(row?.reserved_usd??0);return {budgetUsd,spentUsd,reservedUsd,remainingUsd:Math.max(0,budgetUsd-spentUsd),availableUsd:Math.max(0,budgetUsd-spentUsd-reservedUsd),percentUsed:budgetUsd?Math.min(100,spentUsd/budgetUsd*100):100,periodStart:String(row?.period_start||start),periodEnd:String(row?.period_end||end)};}
export function estimateTextCallReservation(input:string,maxOutputTokens=4000){const inputTokens=Math.ceil(input.length/4)+1200;const inputRate=rate('THEOPHANY_INPUT_USD_PER_MILLION',0.20),outputRate=rate('THEOPHANY_OUTPUT_USD_PER_MILLION',1.20);const estimate=inputTokens/1000000*inputRate+maxOutputTokens/1000000*outputRate;return Math.min(rate('THEOPHANY_MAX_TEXT_RESERVATION_USD',0.05),Math.max(rate('THEOPHANY_MIN_TEXT_RESERVATION_USD',0.01),estimate));}
export function calculateTextUsageCost(usage:any){const inputTokens=Number(usage?.input_tokens||0),outputTokens=Number(usage?.output_tokens||0);const inputRate=rate('THEOPHANY_INPUT_USD_PER_MILLION',0.20),outputRate=rate('THEOPHANY_OUTPUT_USD_PER_MILLION',1.20);return inputTokens/1000000*inputRate+outputTokens/1000000*outputRate;}