import { useEffect, useRef, useState } from 'react';
import { Bot, ChevronDown, Clock3, Menu, Mic, MicOff, Plus, Settings, Sparkles, X, ArrowUp, Check, LoaderCircle } from 'lucide-react';
import './theophany-chat.css';

type Mode = 'chat' | 'voice' | 'agent';
type Msg = { id:string; role:'user'|'assistant'; text:string; events?: any[] };

const suggestions=['Build me a simple website','Create a mobile app','Build a landing page for my business','Help me turn an idea into software'];

export default function App(){
 const [mode,setMode]=useState<Mode>('chat');
 const [menu,setMenu]=useState(false); const [panel,setPanel]=useState<'history'|'settings'|null>(null);
 const [text,setText]=useState(''); const [messages,setMessages]=useState<Msg[]>([]); const [listening,setListening]=useState(false); const [busy,setBusy]=useState(false); const [testing,setTesting]=useState(false);
 const [status,setStatus]=useState(''); const [memoryCount,setMemoryCount]=useState(0); const [automationCount,setAutomationCount]=useState(0); const [connections,setConnections]=useState<any>(null);
 const recognition=useRef<any>(null);
 const [sessionId]=useState(()=>{const key='theophany-session-id';const old=localStorage.getItem(key);if(old)return old;const id=crypto.randomUUID();localStorage.setItem(key,id);return id});
 const refresh=async()=>{try{const [m,a,s]=await Promise.all([fetch(`/api/memory?session_id=${encodeURIComponent(sessionId)}`),fetch(`/api/automation?session_id=${encodeURIComponent(sessionId)}`),fetch('/api/status')]);if(m.ok)setMemoryCount(((await m.json()).memories||[]).length);if(a.ok)setAutomationCount(((await a.json()).jobs||[]).length);if(s.ok)setConnections((await s.json()).configured)}catch{}};
 useEffect(()=>{refresh();return()=>window.speechSynthesis?.cancel()},[]);
 const speak=(value:string,voiceMode:Mode=mode)=>{if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(value);u.rate=voiceMode==='agent'?.9:.98;u.pitch=voiceMode==='agent'?.72:1.08;window.speechSynthesis.speak(u)};
 const listen=()=>{const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setStatus('Voice input is not supported in this browser.');return}if(listening){recognition.current?.stop();return}const r=new SR();r.lang='en-US';r.continuous=false;r.interimResults=true;r.onstart=()=>{setListening(true);setStatus('Listening…')};r.onresult=(e:any)=>{let value='';for(let i=e.resultIndex;i<e.results.length;i++)value+=e.results[i][0].transcript;setText(value)};r.onerror=()=>{setListening(false);setStatus('I could not hear that. Try again.')};r.onend=()=>setListening(false);recognition.current=r;r.start()};
 const build=async()=>{const prompt=text.trim();if(!prompt)return;setText('');setMessages(v=>[...v,{id:crypto.randomUUID(),role:'user',text:prompt}]);setBusy(true);setStatus('Working…');try{const r=await fetch('/api/build',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:prompt,session_id:sessionId})});const d=await r.json();const reply=d.ok?'Done. I built the requested software and sent the result through the existing Theophany build pipeline.':(d.message||'I could not complete that build.');setMessages(v=>[...v,{id:crypto.randomUUID(),role:'assistant',text:reply,events:d.events||[]}]);setStatus('');speak(reply,mode)}catch{const reply='The build service could not be reached.';setMessages(v=>[...v,{id:crypto.randomUUID(),role:'assistant',text:reply}]);setStatus('');speak(reply,mode)}finally{setBusy(false);refresh()}};
 const automate=async()=>{const goal=text.trim();if(!goal){setStatus('Give me a goal first.');return}setText('');setMessages(v=>[...v,{id:crypto.randomUUID(),role:'user',text:goal}]);setBusy(true);setStatus('Running automatically…');try{const r=await fetch('/api/automation',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({goal,session_id:sessionId})});const d=await r.json();const reply=d.ok?'Automation completed.':(d.message||'Automation stopped.');setMessages(v=>[...v,{id:crypto.randomUUID(),role:'assistant',text:reply,events:d.events||[]}]);speak(reply,'agent')}catch{setMessages(v=>[...v,{id:crypto.randomUUID(),role:'assistant',text:'Automation could not be started.'}])}finally{setBusy(false);setStatus('');refresh()}};
 const selfTest=async()=>{setTesting(true);setStatus('Checking services…');try{const r=await fetch('/api/self-test',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});const d=await r.json();setStatus(d.ok?'All configured services passed.':`${d.passed||0}/${d.total||4} services passed.`);refresh()}catch{setStatus('Self-test could not reach the runtime.')}finally{setTesting(false)}};
 const newChat=()=>{setMessages([]);setText('');setStatus('');setPanel(null)};
 const header= <header className='th-top'><div className='th-left'><button className='th-icon' aria-label='Open history' onClick={()=>setPanel(panel==='history'?null:'history')}><Menu size={20}/></button><button className='th-brand' onClick={()=>setMenu(!menu)}><span className='th-mark'><Sparkles size={16}/></span><span>Theophany</span><ChevronDown size={15}/></button></div><div className='th-right'><button className='th-icon' aria-label='New chat' onClick={newChat}><Plus size={20}/></button><button className='th-icon' aria-label='Settings' onClick={()=>setPanel('settings')}><Settings size={19}/></button></div>{menu&&<div className='th-history'><div className='th-history-title'>Choose how to build</div><button className='th-history-item' onClick={()=>{setMode('chat');setMenu(false)}}><Bot size={17}/> Chat</button><button className='th-history-item' onClick={()=>{setMode('voice');setMenu(false)}}><Mic size={17}/> Voice Mode</button><button className='th-history-item' onClick={()=>{setMode('agent');setMenu(false)}}><Sparkles size={17}/> Agent Mode</button></div>}</header>;
 const composer=<div className='th-composer-wrap'><div className='th-composer'><button className='th-mic' onClick={listen} disabled={busy}>{listening?<MicOff size={19}/>:<Mic size={19}/>}</button><textarea value={text} disabled={busy} rows={1} placeholder={mode==='agent'?'Message the agent…':mode==='voice'?'Talk to Theophany…':'Message Theophany…'} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();mode==='agent'?automate():build()}}}/><button className='th-send' onClick={mode==='agent'?automate:build} disabled={busy||!text.trim()}>{busy?<LoaderCircle className='th-spin' size={17}/>:<ArrowUp size={18}/>}</button></div><div className='th-tools'><span>{status||'Theophany can make mistakes. Check important results.'}</span><div className='th-toolset'><button className='th-tool' onClick={()=>speak(text||'I am ready. What should we build?')}>Hear</button>{mode==='agent'&&<button className='th-tool' onClick={automate}>Run automatically</button>}</div></div></div>;
 return <div className='th-app'>{header}<main className='th-main'><div className='th-conversation'>{messages.length===0?<div className='th-empty'><div className='th-logo-large'><Sparkles size={24}/></div><h1>What can I help you build?</h1><div className='th-suggestions'>{suggestions.map(s=><button key={s} className='th-suggestion' onClick={()=>setText(s)}>{s}</button>)}</div></div>:messages.map(m=><article className={`th-message th-${m.role}`} key={m.id}><div className='th-avatar'>{m.role==='user'?'You':<Sparkles size={16}/>}</div><div className='th-message-body'><p>{m.text}</p>{m.events?.length?<div className='th-event-list'>{m.events.map((e:any,i:number)=><div className='th-event' key={i}>{e.done?<Check size={12}/>:<Clock3 size={12}/>}<strong>{e.stage||'Build'}</strong>{e.message||''}</div>)}</div>:null}</div></article>)}</div></main>{composer}{panel&&<div className='th-overlay' onClick={()=>setPanel(null)}><section className='th-sheet' onClick={e=>e.stopPropagation()}><button className='th-icon th-close' onClick={()=>setPanel(null)}><X size={18}/></button>{panel==='history'?<><h3>History</h3>{messages.length?<button className='th-history-item' onClick={newChat}><Plus size={16}/> New chat</button>:<div className='th-row'><span>No conversations in this session</span></div>}</>:<><h3>Theophany</h3><div className='th-row'><span>Mode</span><span>{mode}</span></div><div className='th-row'><span>Memory</span><span className='th-ok'>{memoryCount} stored</span></div><div className='th-row'><span>Automations</span><span>{automationCount}</span></div>{connections&&Object.entries({OpenAI:connections.openai,GitHub:connections.github,Supabase:connections.supabase,Vercel:connections.vercel}).map(([name,ok])=><div className='th-row' key={name}><span>{name}</span><span className={ok?'th-ok':'th-muted'}>{ok?'Connected':'Needs setup'}</span></div>)}<button className='th-history-item' onClick={selfTest} disabled={testing}><LoaderCircle className={testing?'th-spin':''} size={16}/>{testing?'Testing services…':'Run system test'}</button></>}</section></div>}</div>;
}
