import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowUp, ArrowUpRight, Check, ChevronRight, LoaderCircle, MessageCircle, Mic, MicOff, Play, Settings2, Sparkles, Volume2, X } from 'lucide-react';
import './theophany-redesign.css';

type Page='home'|'modes'|'voice'|'agent';
type Mode='voice'|'agent';
type Event={stage:string;message:string;done?:boolean;error?:boolean};
type Connections={openai:boolean;github:boolean;supabase:boolean;vercel:boolean};

export default function AppV3(){
 const [page,setPage]=useState<Page>('home'); const [mode,setMode]=useState<Mode>('voice'); const [text,setText]=useState(''); const [listening,setListening]=useState(false); const [speaking,setSpeaking]=useState(false); const [building,setBuilding]=useState(false); const [automating,setAutomating]=useState(false); const [testing,setTesting]=useState(false); const [events,setEvents]=useState<Event[]>([]); const [status,setStatus]=useState('Ready when you are.'); const [memoryCount,setMemoryCount]=useState(0); const [automationCount,setAutomationCount]=useState(0); const [connections,setConnections]=useState<Connections|null>(null); const [panel,setPanel]=useState<'memory'|'settings'|null>(null); const recognition=useRef<any>(null);
 const [sessionId]=useState(()=>{const k='theophany-session-id';const old=localStorage.getItem(k);if(old)return old;const v=crypto.randomUUID();localStorage.setItem(k,v);return v});
 const loadData=async()=>{try{const [m,a]=await Promise.all([fetch(`/api/memory?session_id=${encodeURIComponent(sessionId)}`),fetch(`/api/automation?session_id=${encodeURIComponent(sessionId)}`)]);if(m.ok)setMemoryCount(((await m.json()).memories||[]).length);if(a.ok)setAutomationCount(((await a.json()).jobs||[]).length)}catch{}};
 const loadConnections=async()=>{try{const r=await fetch('/api/status');if(r.ok)setConnections((await r.json()).configured)}catch{}};
 useEffect(()=>{loadData();loadConnections();return()=>window.speechSynthesis?.cancel()},[]);
 const speak=(value:string,selected=mode)=>{if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const vs=window.speechSynthesis.getVoices();const preferred=selected==='agent'?vs.find(v=>/male|david|daniel|alex|mark|fred|george/i.test(`${v.name} ${v.voiceURI}`)):vs.find(v=>/female|samantha|victoria|karen|zira|susan|moira/i.test(`${v.name} ${v.voiceURI}`));const u=new SpeechSynthesisUtterance(value);if(preferred)u.voice=preferred;u.pitch=selected==='agent'?.72:1.08;u.rate=selected==='agent'?.9:.98;u.onstart=()=>setSpeaking(true);u.onend=()=>setSpeaking(false);window.speechSynthesis.speak(u)};
 const startListening=()=>{const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setStatus('Voice input is not supported in this browser.');return}if(listening){recognition.current?.stop();return}const r=new SR();r.lang='en-US';r.continuous=false;r.interimResults=true;r.onstart=()=>{setListening(true);setStatus(mode==='agent'?'Agent is listening…':'I’m listening…')};r.onresult=(e:any)=>{let t='';for(let i=e.resultIndex;i<e.results.length;i++)t+=e.results[i][0].transcript;setText(t);if(e.results[e.results.length-1].isFinal){setStatus('I heard you. Ready to build.');speak(`I heard: ${t}`,mode)}};r.onerror=()=>{setListening(false);setStatus('I could not hear that. Try again.')};r.onend=()=>setListening(false);recognition.current=r;r.start()};
 const build=async()=>{if(!text.trim()){const m=mode==='agent'?'Tell me what you want me to build.':'Tell me what you want to build first.';setStatus(m);speak(m,mode);return}setBuilding(true);setEvents([]);setStatus(mode==='agent'?'Agent is building…':'I’m building it…');try{const r=await fetch('/api/build',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:text.trim(),session_id:sessionId})});const d=await r.json();setEvents(d.events||[]);setStatus(d.ok?'Build complete.':(d.message||'Build stopped.'));speak(d.ok?'Build complete.':(d.message||'I could not complete the build.'),mode)}catch{setStatus('The build service is not available yet.')}finally{setBuilding(false);loadData();loadConnections()}};
 const automate=async()=>{if(!text.trim()){setStatus('Give me a goal and I will run it automatically.');speak('Give me a goal and I will run it automatically.','agent');return}setAutomating(true);setEvents([]);setStatus('Automation is running…');try{const r=await fetch('/api/automation',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({goal:text.trim(),session_id:sessionId})});const d=await r.json();setEvents(d.events||[]);setStatus(d.ok?'Automation completed.':(d.message||'Automation stopped.'));speak(d.ok?'Automation completed.':(d.message||'Automation failed.'),'agent')}catch{setStatus('Automation could not start.')}finally{setAutomating(false);loadData()}};
 const selfTest=async()=>{setTesting(true);setStatus('Checking Theophany services…');try{const r=await fetch('/api/self-test',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});const d=await r.json();setStatus(d.ok?'All configured services passed.':`${d.passed||0}/${d.total||4} services passed.`);loadConnections()}catch{setStatus('The self-test could not reach the builder runtime.')}finally{setTesting(false)}};
 const busy=building||automating; const visualState=busy?'working':listening?'listening':speaking?'speaking':'idle';
 const Header=({back=false}:{back?:boolean})=><header className='neo-header'><div className='neo-brand'>{back&&<button className='neo-round' onClick={()=>setPage('modes')}><ArrowLeft size={16}/></button>}<div className='neo-brand-symbol'><Sparkles size={16}/></div><span>THEOPHANY</span></div><div className='neo-header-actions'><button className='neo-round' onClick={()=>setPanel('memory')}><MessageCircle size={16}/></button><button className='neo-round' onClick={()=>{setPanel('settings');loadConnections()}}><Settings2 size={16}/></button></div></header>;
 const Composer=()=> <div className='neo-composer'><textarea value={text} onChange={e=>setText(e.target.value)} disabled={busy} rows={1} placeholder={mode==='agent'?'Give the agent a goal…':'Talk or type to Theophany…'} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();build()}}}/><button onClick={build} disabled={busy}><ArrowUp size={18}/></button></div>;
 const Events=()=>events.length?<div className='neo-events'>{events.map((e,i)=><div className='neo-event' key={i}>{e.error?<X size={15}/>:e.done?<Check size={15}/>:<LoaderCircle className='neo-spin' size={15}/>}<div><strong>{e.stage}</strong><span>{e.message}</span></div></div>)}</div>:null;
 const Home=()=> <main className='neo-page neo-home'><Header/><div className='neo-home-aura'/><div className='neo-home-presence'><div className='neo-presence-halo'/><div className='neo-face'><span/><span/><i/></div><div className='neo-presence-shoulders'/></div><div className='neo-home-copy'><div className='neo-kicker'>YOUR AI BUILDER</div><h1>Build software<br/><em>by speaking.</em></h1><p>Give Theophany an idea. It listens, thinks, builds, tests and helps turn your words into real software.</p><button className='neo-primary' onClick={()=>setPage('modes')}>Enter Theophany <ArrowUpRight size={17}/></button><div className='neo-caption'>Voice-first · Human presence · Agent automation</div></div></main>;
 const Modes=()=> <main className='neo-page neo-modes'><Header/><div className='neo-mode-copy'><div className='neo-kicker'>CHOOSE YOUR PRESENCE</div><h1>How do you want<br/>to build today?</h1><p>Same intelligence. Two very different ways to work.</p></div><div className='neo-mode-cards'><button className='neo-mode-card neo-voice-card' onClick={()=>{setMode('voice');setPage('voice')}}><div className='neo-card-art'><div className='neo-card-person'><div className='neo-card-head'/><div className='neo-card-body'/></div></div><div className='neo-kicker'>VOICE MODE</div><h2>Talk naturally.</h2><p>A human-like AI presence with a soft female voice. Speak naturally and watch it listen, think and respond.</p><ChevronRight className='neo-card-arrow'/></button><button className='neo-mode-card neo-agent-card' onClick={()=>{setMode('agent');setPage('agent')}}><div className='neo-card-art'><div className='neo-card-orb'><Sparkles size={22}/></div></div><div className='neo-kicker'>AGENT MODE</div><h2>Give it a goal.</h2><p>A powerful central orb with a deep male voice. Let the agent plan, build, test and automate.</p><ChevronRight className='neo-card-arrow'/></button></div><div className='neo-footer-status'><span>{status}</span><span>{memoryCount} memories · {automationCount} automations</span><button onClick={selfTest} disabled={testing}><Play size={13}/>{testing?'Testing…':'System test'}</button></div></main>;
 const Voice=()=> <main className='neo-page neo-immersive neo-voice'><Header back/><div className='neo-modebar'><span>VOICE MODE</span><span>SOFT FEMALE VOICE</span></div><div className={`neo-human-stage ${visualState}`}><div className='neo-human-aura'/><div className='neo-human-halo'/><div className='neo-human'><div className='neo-human-head'><span/><span/><i/></div><div className='neo-human-neck'/><div className='neo-human-shoulders'/></div><div className='neo-wave'>{[1,2,3,4,5,6,7].map(i=><i key={i}/>)}</div></div><div className='neo-immersive-copy'><div className='neo-kicker'>{visualState==='working'?'BUILDING':visualState==='listening'?'LISTENING':visualState==='speaking'?'SPEAKING':'READY'}</div><h2>{visualState==='working'?'I’m building it.':visualState==='listening'?'I’m listening.':visualState==='speaking'?'I’m here.':'Talk to Theophany.'}</h2><p>{status}</p></div><button className='neo-mic' onClick={startListening} disabled={busy}>{listening?<MicOff/>:busy?<LoaderCircle className='neo-spin'/>:<Mic/>}</button><Composer/><button className='neo-hear' onClick={()=>speak(text||'I am ready. Tell me what you want to build.','voice')}><Volume2 size={14}/>{speaking?'Speaking…':'Hear Theophany'}</button><Events/></main>;
 const Agent=()=> <main className='neo-page neo-immersive neo-agent'><Header back/><div className='neo-modebar'><span>AGENT MODE</span><span>DEEP MALE VOICE</span></div><div className={`neo-orb-stage ${visualState}`} onClick={startListening}><div className='neo-orbit orbit-one'/><div className='neo-orbit orbit-two'/><div className='neo-orbit orbit-three'/><div className='neo-agent-orb'><Sparkles size={36}/></div></div><div className='neo-immersive-copy'><div className='neo-kicker'>{automating?'AUTOMATING':building?'WORKING':listening?'LISTENING':'READY'}</div><h2>{automating?'The automation is running.':building?'The agent is building.':'Give the agent a goal.'}</h2><p>{status}</p></div><Composer/><div className='neo-agent-actions'><button className='neo-hear' onClick={()=>speak(text||'Tell me what you want me to build.','agent')}><Volume2 size={14}/>{speaking?'Speaking…':'Hear Theophany'}</button><button className='neo-agent-button' onClick={automate} disabled={busy}><Sparkles size={14}/>{automating?'Automating…':'Run automatically'}</button><button className='neo-hear' onClick={selfTest} disabled={testing}><Play size={14}/>{testing?'Testing…':'System test'}</button></div><Events/></main>;
 const Panel=()=>panel?<div className='neo-panel-backdrop' onClick={()=>setPanel(null)}><section className='neo-panel' onClick={e=>e.stopPropagation()}><button className='neo-panel-close' onClick={()=>setPanel(null)}><X size={18}/></button>{panel==='memory'?<><div className='neo-kicker'>MEMORY</div><h2>Theophany remembers.</h2><p>Build context is retained for this browser session.</p><div className='neo-row'><span>Session memory</span><strong><Check size={14}/> Active</strong></div><div className='neo-row'><span>Stored memories</span><strong>{memoryCount}</strong></div><div className='neo-row'><span>Automations</span><strong>{automationCount}</strong></div></>:<><div className='neo-kicker'>CONNECTIONS</div><h2>Theophany services.</h2><p>Server-side connection status. Secrets are never shown.</p>{connections?Object.entries({OpenAI:connections.openai,GitHub:connections.github,Supabase:connections.supabase,Vercel:connections.vercel}).map(([name,ok])=><div className='neo-row' key={name}><span>{name}</span><strong className={ok?'ok':''}>{ok?<Check size={14/>:null}{ok?'Connected':'Needs setup'}</strong></div>):<p>Checking connections…</p>}</>}</section></div>:null;
 return <div className='neo-app'>{page==='home'?<Home/>:page==='modes'?<Modes/>:page==='voice'?<Voice/>:<Agent/>}<Panel/></div>;
}
