import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowUp, CheckCircle2, Circle, LoaderCircle, MessageCircle, Mic, MicOff, Play, Settings2, Sparkles, Volume2, X } from 'lucide-react';

type BuildEvent={stage:string;message:string;done?:boolean;error?:boolean};
type Connections={openai:boolean;github:boolean;supabase:boolean;vercel:boolean};
type SelfTest={name:string;message:string;ok:boolean};
type Page='home'|'modes'|'voice'|'agent';
type Mode='voice'|'agent';

export default function App(){
 const [page,setPage]=useState<Page>('home'); const [text,setText]=useState(''); const [listening,setListening]=useState(false); const [speaking,setSpeaking]=useState(false); const [building,setBuilding]=useState(false); const [automating,setAutomating]=useState(false); const [testing,setTesting]=useState(false); const [events,setEvents]=useState<BuildEvent[]>([]); const [status,setStatus]=useState('Ready when you are.'); const [connections,setConnections]=useState<Connections|null>(null); const [selfTest,setSelfTest]=useState<SelfTest[]|null>(null); const [memoryCount,setMemoryCount]=useState(0); const [automationCount,setAutomationCount]=useState(0); const [modal,setModal]=useState<'memory'|'settings'|null>(null); const [activeMode,setActiveMode]=useState<Mode>('voice');
 const [sessionId]=useState(()=>{const k='theophany-session-id';const old=localStorage.getItem(k);if(old)return old;const v=crypto.randomUUID();localStorage.setItem(k,v);return v}); const recognition=useRef<any>(null);
 const speak=(value:string,mode:Mode=activeMode)=>{if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const vs=window.speechSynthesis.getVoices();const preferred=mode==='agent'?vs.find(v=>/male|david|daniel|alex|mark|fred|george/i.test(`${v.name} ${v.voiceURI}`)):vs.find(v=>/female|samantha|victoria|karen|zira|susan|moira/i.test(`${v.name} ${v.voiceURI}`));const u=new SpeechSynthesisUtterance(value);if(preferred)u.voice=preferred;u.pitch=mode==='agent'?.72:1.08;u.rate=mode==='agent'?.9:.98;u.onstart=()=>setSpeaking(true);u.onend=()=>setSpeaking(false);window.speechSynthesis.speak(u)};
 const loadConnections=async()=>{try{const r=await fetch('/api/status');if(r.ok)setConnections((await r.json()).configured)}catch{}};
 const loadMemoryAutomation=async()=>{try{const [m,a]=await Promise.all([fetch(`/api/memory?session_id=${encodeURIComponent(sessionId)}`),fetch(`/api/automation?session_id=${encodeURIComponent(sessionId)}`)]);if(m.ok)setMemoryCount(((await m.json()).memories||[]).length);if(a.ok)setAutomationCount(((await a.json()).jobs||[]).length)}catch{}};
 const runSelfTest=async()=>{setTesting(true);setSelfTest(null);setStatus('Checking Theophany services…');try{const r=await fetch('/api/self-test',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});const d=await r.json();setSelfTest(d.stages||[]);setStatus(d.ok?'All configured services passed.':`${d.passed||0}/${d.total||4} services passed.`);speak(d.ok?'All configured services passed.':`${d.passed||0} of ${d.total||4} services passed.`,activeMode)}catch{setStatus('The self-test could not reach the builder runtime.')}finally{setTesting(false);loadConnections()}};
 const startListening=()=>{const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setStatus('Voice input is not supported in this browser.');return}if(listening){recognition.current?.stop();return}const r=new SR();r.lang='en-US';r.continuous=false;r.interimResults=true;r.onstart=()=>{setListening(true);setStatus(activeMode==='agent'?'Agent is listening…':'I’m listening…')};r.onresult=(e:any)=>{let t='';for(let i=e.resultIndex;i<e.results.length;i++)t+=e.results[i][0].transcript;setText(t);if(e.results[e.results.length-1].isFinal){setStatus('I heard you. Ready to build.');speak(`I heard: ${t}`,activeMode)}};r.onerror=()=>{setListening(false);setStatus('I could not hear that. Try again.')};r.onend=()=>setListening(false);recognition.current=r;r.start()};
 const send=async()=>{if(!text.trim()){const m=activeMode==='agent'?'Tell me what you want me to build.':'Tell me what you want to build first.';setStatus(m);speak(m,activeMode);return}setBuilding(true);setEvents([]);setStatus(activeMode==='agent'?'Agent is building…':'I’m building it…');try{const r=await fetch('/api/build',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:text.trim(),session_id:sessionId})});const d=await r.json();setEvents(d.events||[]);setStatus(d.ok?'Build complete.':(d.message||'Build stopped.'));speak(d.ok?'Build complete.':(d.message||'I could not complete the build.'),activeMode)}catch{setStatus('The build service is not available yet.')}finally{setBuilding(false);loadConnections();loadMemoryAutomation()}};
 const runAutomation=async()=>{if(!text.trim()){setStatus('Give me a goal and I will run it as an automated build.');speak('Give me a goal and I will run it as an automated build.','agent');return}setAutomating(true);setEvents([]);setStatus('Automation is running…');try{const r=await fetch('/api/automation',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({goal:text.trim(),session_id:sessionId})});const d=await r.json();setEvents(d.events||[]);setStatus(d.ok?'Automation completed.':(d.message||'Automation stopped.'));speak(d.ok?'Automation completed.':(d.message||'Automation failed.'),'agent')}catch{setStatus('Automation could not start.')}finally{setAutomating(false);loadMemoryAutomation()}};
 useEffect(()=>{loadConnections();loadMemoryAutomation();return()=>window.speechSynthesis?.cancel()},[]);
 const Nav=({back=false}:{back?:boolean})=><header className='v2-nav'><div className='v2-brand'>{back&&<button className='v2-icon' onClick={()=>setPage('modes')}><ArrowLeft size={16}/></button>}<div className='v2-brand-mark'><Sparkles size={17}/></div><span>THEOPHANY</span></div><div className='v2-nav-actions'><button className='v2-icon' onClick={()=>setModal('memory')}><MessageCircle size={17}/></button><button className='v2-icon' onClick={()=>{setModal('settings');loadConnections()}}><Settings2 size={17}/></button></div></header>;
 const Composer=()=> <div className='v2-composer'><textarea value={text} disabled={building||automating} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder={activeMode==='agent'?'Give the agent a goal…':'Talk or type to Theophany…'} rows={1}/><button className='v2-send' onClick={send} disabled={building||automating}><ArrowUp size={18}/></button></div>;
 const Build=()=>events.length?<section className='v2-build'>{events.map((e,i)=><div className='v2-event' key={i}>{e.error?<Circle size={15}/>:e.done?<CheckCircle2 size={15}/>:<LoaderCircle className='v2-spin' size={15}/>}<div><strong>{e.stage}</strong><span>{e.message}</span></div></div>)}</section>:null;
 const Home=()=> <section className='v2-shell'><Nav/><div className='v2-hero'><div className='v2-hero-glow'/><div className='v2-presence'><div className='v2-face'><i/><i/><span/></div></div><div className='v2-hero-content'><div className='v2-eyebrow'>YOUR AI BUILDER</div><h1>Build software<br/><span>by speaking.</span></h1><p>Give Theophany an idea. It listens, thinks, builds and helps turn your words into real software.</p><button className='v2-primary' onClick={()=>setPage('modes')}>Enter Theophany <ArrowUp size={17}/></button><div className='v2-note'>A voice-first interface. No coding workspace required.</div></div></div></section>;
 const Modes=()=> <section className='v2-shell v2-mode-screen'><Nav/><div className='v2-mode-intro'><div className='v2-eyebrow'>CHOOSE YOUR PRESENCE</div><h1>How do you want<br/>to build today?</h1><p>Two ways to work with the same intelligence.</p></div><div className='v2-mode-grid'><button className='v2-mode voice' onClick={()=>{setActiveMode('voice');setPage('voice')}}><div className='v2-mode-visual'><div className='v2-mini-person'/></div><div className='v2-eyebrow'>VOICE MODE</div><h2>Talk to Theophany.</h2><p>A human-like AI presence with a soft female voice. Speak naturally and watch it listen, think and respond.</p><ArrowUp className='v2-mode-arrow' size={22}/></button><button className='v2-mode agent' onClick={()=>{setActiveMode('agent');setPage('agent')}}><div className='v2-mode-visual'><div className='v2-mini-orb'/></div><div className='v2-eyebrow'>AGENT MODE</div><h2>Give it a goal.</h2><p>A powerful central orb with a deep male voice. Let the agent plan, build, test and automate.</p><ArrowUp className='v2-mode-arrow' size={22}/></button></div><div className='v2-status-row'><span>{status} · {memoryCount} memories · {automationCount} automations</span><button className='v2-small-btn' onClick={runSelfTest} disabled={testing}><Play size={14}/>{testing?'Testing…':'Builder test'}</button></div>{selfTest&&<section className='v2-tests'>{selfTest.map((s,i)=><div className='v2-test' key={i}>{s.ok?<CheckCircle2 size={15}/>:<Circle size={15}/>}<div><strong>{s.name}</strong><span>{s.message}</span></div></div>)}</section>}</section>;
 const Voice=()=> <section className='v2-shell v2-immersive'><Nav back/><div className='v2-immersive-head'><span>VOICE MODE · SOFT FEMALE VOICE</span><span>{building?'BUILDING':listening?'LISTENING':speaking?'SPEAKING':'READY'}</span></div><div className={`v2-ai-stage ${listening?'v2-listening':''} ${speaking?'v2-speaking':''}`}><div className='v2-human-aura'/><div className='v2-human'><div className='v2-human-head'><i/><i/><span/></div><div className='v2-human-neck'/><div className='v2-human-body'/></div></div><div className='v2-wave'>{[1,2,3,4,5,6,7].map(i=><i key={i}/>)}</div><h2>{building?'I’m building it.':listening?'I’m listening.':speaking?'I’m here.':'Talk to Theophany.'}</h2><p>{building?'Your idea is moving through the build pipeline.':status}</p><button className='v2-mic' onClick={startListening}>{building?<LoaderCircle className='v2-spin'/>:listening?<MicOff/>:<Mic/>}</button><Composer/><button className='v2-small-btn' style={{marginTop:10}} onClick={()=>speak(text||'I am ready. Tell me what you want to build.','voice')}><Volume2 size={14}/>{speaking?'Speaking…':'Hear Theophany'}</button><Build/></section>;
 const Agent=()=> <section className='v2-shell v2-immersive'><Nav back/><div className='v2-immersive-head'><span>AGENT MODE · DEEP MALE VOICE</span><span>{automating?'AUTOMATING':building?'WORKING':'READY'}</span></div><div className={`v2-agent-stage ${listening?'v2-orb-listening':''} ${building||automating?'v2-orb-working':''}`} onClick={startListening} role='button' tabIndex={0}><div className='v2-orb-ring'/><div className='v2-orb-ring two'/><div className='v2-orb'><Sparkles size={34}/></div></div><h2>{automating?'The automation is running.':building?'The agent is building.':'Give the agent a goal.'}</h2><p>{automating?'Theophany is executing the goal step by step.':building?status:'Describe the product, feature or system you want created.'}</p><Composer/><div className='v2-agent-actions'><button className='v2-small-btn' onClick={()=>speak(text||'Tell me what you want me to build.','agent')}><Volume2 size={14}/>{speaking?'Speaking…':'Hear Theophany'}</button><button className='v2-small-btn' onClick={runAutomation} disabled={automating||building}><Sparkles size={14}/>{automating?'Automating…':'Run automatically'}</button><button className='v2-small-btn' onClick={runSelfTest} disabled={testing}><Play size={14}/>{testing?'Testing…':'System test'}</button></div><Build/></section>;
 return <div className='v2'>{page==='home'?<Home/>:page==='modes'?<Modes/>:page==='voice'?<Voice/>:<Agent/>}<div className='v2-noise'/>{modal&&<div className='v2-modal-backdrop'><div className='v2-modal'><button className='v2-close' onClick={()=>setModal(null)}><X/></button>{modal==='memory'?<><div className='v2-eyebrow'>MEMORY</div><h2>Theophany remembers.</h2><p className='v2-muted'>{memoryCount?`${memoryCount} memories are stored for this browser session.`:'Important build context will appear here after you start building.'}</p><div className='v2-service'><span>Session memory</span><span className='v2-ok'><CheckCircle2 size={15}/>Active</span></div><div className='v2-service'><span>Automations</span><span className='v2-ok'><CheckCircle2 size={15}/>{automationCount} recorded</span></div></>:<><div className='v2-eyebrow'>CONNECTIONS</div><h2>Theophany services.</h2><p className='v2-muted'>Server-side connection status. Secrets are never shown.</p>{connections?[['OpenAI',connections.openai],['GitHub',connections.github],['Supabase',connections.supabase],['Vercel',connections.vercel]].map(([n,ok])=><div className='v2-service' key={String(n)}><span>{String(n)}</span><span className='v2-ok'>{ok?<CheckCircle2 size={15}/>:<Circle size={15}/>} {ok?'Connected':'Needs setup'}</span></div>):<p className='v2-muted'>Checking connections…</p>}</>}</div></div>}</div>
}